name: artifact

on: push

env:
  COUNTRY: "Brazil"

jobs:
  job1:
    name: Artifact Job
    runs-on: ubuntu-latest
    steps:
      - name: use checkout
        uses: actions/checkout@v2
      - name: use artifact
        uses: actions/upload-artifact@v2
        with:
          name: $COUNTRY - ${{ env.COUNTRY }}
          path: .
      - name: Show country
        run: echo $COUNTRY
